name: Deploy

on:
  push:
    branches: [ openout ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudron CLI
        run: npm i -g cloudron

      - name: Run deploy script
        env:
          CLOUDRON_CLI_AUTH_TOKEN: ${{ secrets.CLOUDRON_TOKEN }}
        run: cloudron --server "${{ secrets.CLOUDRON_SERVER }}" exec --app "${{ secrets.CLOUDRON_APP }}" -- /app/data/deploy.sh
